### PR TITLE
Fix simple cipher

### LINKED ISSUE #399: Fix code styles of all example solutions
~~**Blocked by #373**~~

---

We already have ~~an issue to add~~ added linting capabilities to our codebase using eslint. Now we need to make all exercise files compliant with the linting rules. 

We will be spitting it up into exercises and would like to have a separate PR for each exercise.

**Ready to go:**
Below is a list of all files that need linting along with the ones which are already linted (checked).
See the full list of exercises here: https://github.com/exercism/javascript/tree/master/exercises

- [x] accumulate
- [x] acronym
- [x] all-your-base
- [x] allergies
- [x] alphametics
- [x] anagram
- [x] atbash-cipher
- [x] beer-song
- [x] binary
- [x] binary-search
- [x] binary-search-tree
- [x] bob
- [x] bowling
- [x] bracket-push
- [x] change
- [x] circular-buffer
- [x] clock
- [x] collatz-conjecture
- [x] connect
- [x] crypto-square
- [x] custom-set
- [x] diamond
- [x] difference-of-squares
- [x] diffie-hellman
- [x] etl
- [x] flatten-array
- [x] food-chain
- [x] forth
- [x] gigasecond
- [x] grade-school
- [x] grains
- [x] hamming
- [x] hello-world
- [x] hexadecimal
- [x] isbn-verifier
- [x] isogram
- [x] kindergarten-garden
- [x] largest-series-product
- [x] leap
- [x] linked-list
- [x] list-ops
- [x] luhn
- [x] matrix
- [x] meetup
- [x] minesweeper
- [x] nth-prime
- [x] nucleotide-count
- [x] ocr-numbers
- [x] octal
- [x] palindrome-products
- [x] pangram
- [x] pascals-triangle
- [x] perfect-numbers
- [x] phone-number
- [x] pig-latin
- [x] point-mutations
- [x] prime-factors
- [x] protein-translation
- [x] proverb
- [x] pythagorean-triplet
- [x] queen-attack
- [x] raindrops
- [x] reverse-string
- [x] rna-transcription
- [x] robot-name
- [ ] robot-simulator
- [x] roman-numerals
- [x] run-length-encoding
- [x] saddle-points
- [x] say
- [x] scrabble-score
- [x] secret-handshake
- [x] series
- [x] sieve
- [ ] simple-cipher
- [x] simple-linked-list
- [x] space-age
- [x] strain
- [x] sublist
- [x] sum-of-multiples
- [x] transpose
- [x] triangle
- [x] trinary
- [x] twelve-days
- [x] two-bucket
- [x] two-fer
- [x] word-count
- [x] wordy
- [x] zipper

Our CI will check against the linting rules, but since they are not yet implemented for exercises, the [respective directories have been ignored](https://github.com/exercism/javascript/blob/master/.eslintignore).

**Task**
1. Pick one exercise from list of exercises - see if it is not already implemented in the above list (it should not be checked).
2. Comment here that you are working on that exercise.
3. Remove the exercise line from [`.eslintignore`](https://github.com/exercism/javascript/blob/master/.eslintignore)
4. Run `npm run lint` and see all linting errors. 
5. Some of these are auto-fixable using `npm run lint-fix`., others have to be fixed manually.
6. Commit and submit a PR 🎉 

**Note:** Please do not fix `big-integer.js` and `big-integer.spec.js` since those are third party code (for compatibility reasons) and we don't want to touch that. Let it remain in `eslintignore`.

### PR DESCRIPTION
**Pull request by leahzxxz**
Closes #399

### CODE REVIEW

**Comment by leahzxxz** [comment]
@matthewmorgan hi! not sure why travis is failing - looks like some of the specs failed. i changed some code on the spec file to correct lint errors - maybe i missed something there?

File: exercises/simple-cipher/example.js [hunk 1]
```diff
@@ -1,10 +1,10 @@
 'use strict';
 
-var ALPHABET = 'abcdefghijklmnopqrstuvwxyz';
+const ALPHABET = 'abcdefghijklmnopqrstuvwxyz';
```
Comment (matthewmorgan) [inline exercises/simple-cipher/example.js]: As I mentioned in the previous PR, we want to always use `var` on this track.

File: exercises/simple-cipher/simple-cipher.spec.js [hunk 2]
```diff
@@ -26,21 +26,15 @@ describe('Random key cipher', function () {
 
 describe('Incorrect key cipher', function () {
   xit('throws an error with an all caps key', function () {
-    expect( function () {
-      new Cipher('ABCDEF');
-    }).toThrow(new Error('Bad key'));
+    expect(new Cipher('ABCDEF')).toThrow(new Error('Bad key'));
```
Comment (matthewmorgan) [inline exercises/simple-cipher/simple-cipher.spec.js]: You should revert this change.  The `toThrow` matcher requires a function as an argument, but your change provides it with a `Cipher` object instead.  

I imagine you were seeing an error for the eslint `no-new` rule.  You can disable for this test block with:
```javascript
  /* eslint-disable no-new */
describe('Incorrect key cipher', function () {
...
});
  /* eslint-enable no-new */
```

File: exercises/simple-cipher/example.js [hunk 3]
```diff
@@ -17,14 +17,14 @@ function randomUpTo(n) {
 module.exports = function (userDefinedKey) {
   var key;
 
-  function addEncodedCharacter(character, index, array) {
+  function addEncodedCharacter(character, index) {
     /* jshint validthis:true */
```
Comment (matthewmorgan) [inline exercises/simple-cipher/example.js]: Hmm...I missed this the first time around.  We should remove these jshint directives.  I'm not sure if they were merged inadvertently or are artifacts of an older linting setup, but they don't make sense anymore.

File: exercises/simple-cipher/simple-cipher.spec.js [hunk 4]
```diff
@@ -24,21 +24,22 @@ describe('Random key cipher', function () {
...
       new Cipher('12345');
     }).toThrow(new Error('Bad key'));
   });
 
   xit('throws an error with an empty key', function () {
-    expect( function () {
+    expect(function () {
       new Cipher('');
     }).toThrow(new Error('Bad key'));
   });
```
Comment (matthewmorgan) [inline exercises/simple-cipher/simple-cipher.spec.js]: Be sure to add the complementary `enable` line for the eslint rule.

File: exercises/simple-cipher/example.js [hunk 5]
```diff
@@ -17,14 +17,14 @@ function randomUpTo(n) {
...
     var i = ALPHABET.indexOf(character) + ALPHABET.indexOf(key[index % key.length]);
     if (i >= ALPHABET.length) { i -= ALPHABET.length; }
     this.push(ALPHABET[i]);
   }
 
-  function addDecodedCharacter(character, index, array) {
+  function addDecodedCharacter(character, index) {
     /* jshint validthis:true */
```
Comment (matthewmorgan) [inline exercises/simple-cipher/example.js]: Remove please.

**Comment by matthewmorgan** [comment]
PS very excited to see that this is the final issue to resolve #399!!

File: exercises/simple-cipher/simple-cipher.spec.js (hunk 4 above)
Comment (matthewmorgan) [reply exercises/simple-cipher/simple-cipher.spec.js]: No problem.

You need to define the _end_ of the `disable` block, otherwise the entire rest of the file will be ignored for that ESlint rule.  EG:


```javascript
  /* eslint-disable no-new */
describe('Incorrect key cipher', function () {
...
});
  /* eslint-enable no-new */
```

Notice that this block begins with `disable` and ends with `enable`, which turns that linting rule back on.

Comment (leahzxxz) [reply exercises/simple-cipher/simple-cipher.spec.js]: Thanks for explaining! Just pushed the change. Final issue woohoo!

**Comment by matthewmorgan** [comment]
Nice work!

One more question: do you feel comfortable squashing your work to a single commit?  If not, I am happy to help with that.

**Comment by matthewmorgan** [comment]
I can just squash and merge ;)
I was suggesting that you do it (if you haven't before) to learn how.  It's not hard.

You could do it like this:
```bash
git checkout master
git pull upstream/master  # or however you have named the exercism/javascript remote
git checkout fix/simple-cipher
git rebase master  # this will replay your changes in a single commit onto master
```

Assuming you don't have any merge conflicts, just force-push your branch back up to your fork:

```bash
git push -f origin fix/simple-cipher
```

Care to give it a try?

**Comment by leahzxxz** [comment]
@matthewmorgan thanks for the instructions! just rebased and fixed merge conflicts. Doesn't look like my commits are squashed though... Did I do it right 😝

**Comment by matthewmorgan** [comment]
One more step-- needed to make sure you were sync'd up with master (that was the hardest part.)

Let's see if we can get this done before anyone merges anything else in ahead of us.

```bash
git reset --soft fd567086481e7b85a5bbbb406b905acab72db6bb # last commit on master before your new ones
git commit -am 'Fix linting errors for simple-cipher'
git push -f origin fix/simple-cipher
```

**Comment by leahzxxz** [comment]
@matthewmorgan Done! let me know if you need anything else. Really appreciate all the guidance!

**Comment by matthewmorgan** [comment]
No problem!  Nice work, thanks for your contributions.
